const state={cases:[],detail:null,list:{page:1,page_size:12,total:0,total_pages:0,status_counts:{},attention:{}},rules:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const statusNames={draft:'草稿',validated:'已校验',under_review:'联合会审',revision_required:'待整改',resubmitted:'整改复核',approved:'已批准'};
const actionNames={create_case:'创建草稿',update_draft:'编辑草稿',validate_case:'技术校验',start_review:'提交会审',submit_opinion:'专业意见',submit_revision:'整改提交',approve_case:'批准归档'};
const disciplineNames={arboriculture:'树木养护',construction:'施工协调'};
const changeNames={new:'新增',continued:'持续',eliminated:'已消除'};
const outcomeNames={pass:'通过',warning:'警示',blocker:'阻断'};
const planLabels={tree_code:'古树编号',species:'树种',age_years:'树龄',health_grade:'健康等级',source_location:'迁出位置',destination_location:'迁入位置',migration_reason:'迁移理由',construction_window:'施工窗口',protection_measures:'保护措施',trunk_diameter_cm:'胸径',root_ball_diameter_cm:'土球直径',transport_duration_hours:'运输时长',destination_ready:'迁入地准备'};
const issueFields=['migration_reason','protection_measures','construction_window','destination_location','source_location','tree_code','species','health_grade','age_years','trunk_diameter_cm','root_ball_diameter_cm','transport_duration_hours','destination_ready'];
function requestID(){return crypto.randomUUID()}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({error:{message:'响应格式无效'}}));if(!response.ok){const e=new Error(data.error?.message||'请求失败');e.data=data;e.status=response.status;throw e}return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function filterQuery(){const d=new FormData($('#case-filters')),params=new URLSearchParams();for(const [key,value] of d)if(String(value).trim())params.set(key,String(value).trim());params.set('page',state.list.page);params.set('page_size',state.list.page_size);return params}
async function loadCases(selectID){const data=await api(`/api/cases?${filterQuery()}`);state.cases=data.cases||[];state.list={...state.list,...data};renderCaseList();if(selectID)await selectCase(selectID);else if(!state.detail&&state.cases.length)await selectCase(state.cases[0].id)}
function renderCaseList(){$('#case-count').textContent=state.list.total||0;$('#case-list').innerHTML=state.cases.map(c=>`<button class="case-link ${state.detail?.case.id===c.id?'active':''}" data-id="${escapeHTML(c.id)}"><strong>${escapeHTML(c.plan.tree_code)} · ${escapeHTML(c.plan.species)}</strong><span>${statusNames[c.status]} · r${c.revision}</span></button>`).join('')||'<p class="rail-empty">当前筛选无结果</p>';$$('.case-link').forEach(b=>b.onclick=()=>selectCase(b.dataset.id));const counts=state.list.status_counts||{},attention=state.list.attention||{};$('#queue-stats').innerHTML=`<div class="status-totals">${Object.entries(statusNames).map(([key,label])=>`<span>${label}<strong>${counts[key]||0}</strong></span>`).join('')}</div><p>阻断关注 ${attention.blocking_findings||0} · 待席位 ${attention.pending_seats||0} · 待响应 ${attention.pending_responses||0}</p>`;const pages=state.list.total_pages||0;$('#page-label').textContent=`${state.list.page} / ${pages||1}`;$('#prev-page').disabled=state.list.page<=1;$('#next-page').disabled=pages===0||state.list.page>=pages}
async function selectCase(id){state.detail=await api(`/api/cases/${encodeURIComponent(id)}`);$('#empty-state').hidden=true;$('#case-view').hidden=false;render();renderCaseList()}
function render(){const c=state.detail.case,p=c.plan;$('#tree-code').textContent=p.tree_code;$('#case-title').textContent=`${p.species} · ${p.age_years} 年`;$('#case-location').textContent=`${p.source_location} → ${p.destination_location}`;$('#status-badge').textContent=statusNames[c.status];$('#revision-label').textContent=`revision ${c.revision}`;renderTimeline(c);renderActions(c);renderApprovalChecks();renderAudit();renderPlan(p);renderValidationBatches(c);renderReviews(c);renderVersions(c);renderArchive(c)}
function renderTimeline(c){const order=['draft','validated','under_review','revision_required','resubmitted','approved'],current=order.indexOf(c.status);$('#timeline').innerHTML=order.map((s,i)=>`<li class="${i<=current?'done':''}">${statusNames[s]}</li>`).join('')}
function action(label,fn,primary=false){const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.onclick=fn;$('#action-bar').append(b)}
function renderActions(c){const bar=$('#action-bar');bar.innerHTML='';if(c.status==='draft'){action('编辑方案',()=>openCaseDialog(c));action('执行规则校验',()=>mutate('validate',{}).catch(()=>{}),true)}if(c.status==='validated'){action('再次校验',()=>mutate('validate',{}).catch(()=>{}));action('提交联合会审',()=>mutate('review',{}).catch(()=>{}),true)}if(c.status==='under_review')action('提交专业意见',openReviewDialog,true);if(c.status==='revision_required')action('提交整改版本',openRevisionDialog,true);if(c.status==='resubmitted')action('批准归档',approve,true)}
function renderApprovalChecks(){const v=state.detail.approval_verification;if(!v){$('#approval-checks').innerHTML='';return}$('#approval-checks').innerHTML=`<strong>批准前核验</strong>${v.checks.map(x=>`<span class="check-result ${x.passed?'pass':'fail'}" title="${escapeHTML(x.message)}">${x.passed?'✓':'!'} ${escapeHTML(x.label)}</span>`).join('')}`}
function renderAudit(){const events=state.detail.audit_events||[],actionSelect=$('#audit-action'),selected=actionSelect.value;actionSelect.innerHTML='<option value="">全部操作</option>'+[...new Set(events.map(x=>x.action))].map(x=>`<option value="${escapeHTML(x)}">${escapeHTML(actionNames[x]||x)}</option>`).join('');actionSelect.value=selected;const revision=Number($('#audit-revision').value)||0,actionFilter=actionSelect.value;$('#audit-events').innerHTML=events.filter(x=>(!actionFilter||x.action===actionFilter)&&(!revision||x.revision===revision)).sort((a,b)=>a.sequence-b.sequence).map(x=>`<article class="data-row audit-row"><h3>#${x.sequence} ${escapeHTML(actionNames[x.action]||x.action)} · r${x.revision}</h3><p>${escapeHTML(x.actor)} · ${escapeHTML(x.result)}</p><p>${escapeHTML(statusNames[x.from_status]||'开始')} → ${escapeHTML(statusNames[x.to_status]||x.to_status)} · ${new Date(x.timestamp).toLocaleString()}</p><span class="tag">request ${shortRequestID(x.request_id)}</span></article>`).join('')||'<p>当前条件无审计记录。</p>'}
function shortRequestID(value){const v=String(value||'');return escapeHTML(v.length>14?`${v.slice(0,8)}…${v.slice(-4)}`:v)}
function renderPlan(p){$('#plan-detail').innerHTML=Object.entries(planLabels).map(([key,label])=>`<div class="${['migration_reason','protection_measures'].includes(key)?'wide':''}"><dt>${label}</dt><dd>${formatValue(key,p[key])}</dd></div>`).join('')}
function formatValue(key,v){if(key==='destination_ready')return v?'已完成':'未完成';if(key==='age_years')return `${v} 年`;if(key.includes('_cm'))return `${v} cm`;if(key==='transport_duration_hours')return `${v} 小时`;return escapeHTML(String(v))}
function renderValidationBatches(c){const batches=c.validation_batches||[],select=$('#batch-select');select.innerHTML=batches.map((b,i)=>`<option value="${escapeHTML(b.id)}">第 ${i+1} 批 · r${b.case_revision} · ${escapeHTML(b.rule_version)}</option>`).join('')||'<option>尚无批次</option>';select.disabled=!batches.length;if(batches.length){select.value=batches[batches.length-1].id;renderBatch(select.value)}else{$('#batch-summary').textContent='';$('#finding-count').textContent='';$('#findings').innerHTML='<p>尚未执行规则校验。</p>'}}
function renderBatch(id){const c=state.detail.case,b=(c.validation_batches||[]).find(x=>x.id===id);if(!b)return;const blockers=b.findings.filter(x=>x.severity==='blocker').length,warnings=b.findings.filter(x=>x.severity==='warning').length;$('#finding-count').textContent=b.findings.length||'';$('#batch-summary').textContent=`${new Date(b.evaluated_at).toLocaleString()} · 阻断 ${blockers} · 警示 ${warnings}`;$('#findings').innerHTML=b.conclusions.length?b.conclusions.map(x=>`<article class="data-row ${x.current_severity||'resolved'}"><h3>${escapeHTML(x.rule_code)} · ${changeNames[x.change]}</h3><p>${escapeHTML(x.current_message||'本批次已无该项结论')}</p><span class="tag">${escapeHTML(planLabels[x.field_path]||x.field_path)}</span><span class="tag">证据：${escapeHTML(x.current_evidence||x.previous_evidence||'无')}</span><p class="applicability">${escapeHTML(x.applicability)}</p></article>`).join(''):'<p>本批次无阻断项或警示项。</p>'}
function renderReviews(c){$('#opinion-count').textContent=c.opinions?.length||'';$('#review-seats').innerHTML=(c.review_seats||[]).map(s=>`<div class="seat"><strong>${disciplineNames[s.discipline]}</strong><span>${s.completed?'已提交':'待审查'}</span></div>`).join('');$('#opinions').innerHTML=(c.opinions||[]).map(o=>`<article class="data-row"><h3>${disciplineNames[o.discipline]} · ${escapeHTML(o.reviewer_name)}</h3><p>结论：${o.conclusion==='pass'?'通过':'需要整改'}　依据：${escapeHTML(o.basis)}</p>${o.issues.map(i=>`<p><span class="tag">${escapeHTML(i.code)}</span>${escapeHTML(i.title)} · ${escapeHTML(planLabels[i.field_path]||i.field_path)}：${escapeHTML(i.suggestion)}</p>`).join('')}</article>`).join('');$('#modifications').innerHTML=c.modification_items?.length?`<h3>结构化修改清单</h3>${c.modification_items.map(i=>`<div class="data-row"><span class="tag">${i.resolved?'已解决':'待响应'}</span><strong>${escapeHTML(i.issue_code)} · ${escapeHTML(i.title)}</strong><p>${disciplineNames[i.discipline]} · ${escapeHTML(i.reviewer_name)} · ${escapeHTML(i.basis)}</p><p>${escapeHTML(i.suggestion)}</p></div>`).join('')}`:''}
function renderVersions(c){$('#versions').innerHTML=c.revision_submissions?.length?c.revision_submissions.map(v=>`<article class="data-row version-row"><h3>revision ${v.from_revision} → ${v.to_revision} · 规则 ${escapeHTML(v.rule_version)}</h3><p>提交人：${escapeHTML(v.submitted_by)} · ${new Date(v.submitted_at).toLocaleString()}</p><h4>字段差异</h4>${v.field_changes.map(x=>`<p><span class="tag">${escapeHTML(planLabels[x.field]||x.field)}</span><del>${escapeHTML(x.before)}</del> → <ins>${escapeHTML(x.after)}</ins></p>`).join('')||'<p>方案字段未变化。</p>'}<h4>逐条响应</h4>${v.issue_responses.map(x=>`<p><span class="tag">${escapeHTML(x.issue_code)}</span>${escapeHTML(x.response)}${x.no_change_reason?` · 无需变更：${escapeHTML(x.no_change_reason)}`:''}</p>`).join('')}<h4>规则影响链</h4>${v.field_rule_impacts.map(x=>`<p><span class="tag">${escapeHTML(planLabels[x.field]||x.field)}</span>${x.no_recalculation?'无需规则复算':`触发 ${x.rule_codes.map(escapeHTML).join('、')}`}</p>`).join('')}${v.rule_impacts.map(x=>`<p class="impact ${x.disposition}"><strong>${escapeHTML(x.rule_code)}</strong> ${x.disposition==='recalculated'?'重算':'延续'}：${outcomeNames[x.before_outcome]} → ${outcomeNames[x.after_outcome]} <span>${escapeHTML(x.reason)}</span></p>`).join('')}<h4>附件</h4>${v.attachment_metadata.map(x=>`<p>${escapeHTML(x.name)} · ${escapeHTML(x.content_type)} · ${x.size_bytes} bytes · ${escapeHTML(x.digest)}</p>`).join('')||'<p>无附件。</p>'}</article>`).join(''):'<p>尚无整改版本。</p>'}
function renderArchive(c){const a=c.approval,v=state.detail.approval_verification;$('#archive').innerHTML=a?`<div class="approved ${v.archive_status==='mismatch'?'archive-alert':''}"><h3>批准决定：已批准</h3><p>批准人：${escapeHTML(a.approver_name)}　批准时间：${new Date(a.approved_at).toLocaleString()}</p><p>${escapeHTML(a.decision_note||'无补充意见')}</p><p class="archive-state">${v.archive_status==='verified'?'摘要已验证':'档案摘要不一致'}</p><p class="digest">SHA-256 ${escapeHTML(a.content_digest)}</p></div>`:'<p>尚未形成批准档案。</p>'}
function planFromForm(form){const d=new FormData(form);return{tree_code:d.get('tree_code'),species:d.get('species'),age_years:Number(d.get('age_years')),health_grade:d.get('health_grade'),source_location:d.get('source_location'),destination_location:d.get('destination_location'),migration_reason:d.get('migration_reason'),construction_window:d.get('construction_window'),protection_measures:d.get('protection_measures'),trunk_diameter_cm:Number(d.get('trunk_diameter_cm')),root_ball_diameter_cm:Number(d.get('root_ball_diameter_cm')),transport_duration_hours:Number(d.get('transport_duration_hours')),destination_ready:d.get('destination_ready')==='on'}}
function openCaseDialog(c){const form=$('#case-form');form.reset();$('#form-title').textContent=c?'编辑方案':'新建方案';form.dataset.mode=c?'edit':'create';if(c)setPlanForm(form,c.plan);$('#form-errors').textContent='';$('#case-dialog').showModal()}
function setPlanForm(form,plan){Object.entries(plan).forEach(([k,v])=>{const el=form.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=Boolean(v);else el.value=v})}
async function saveCase(e){e.preventDefault();const form=e.currentTarget,plan=planFromForm(form);try{let c;if(form.dataset.mode==='edit'){const current=state.detail.case;c=await api(`/api/cases/${current.id}`,{method:'PATCH',body:JSON.stringify({request_id:requestID(),revision:current.revision,plan})})}else c=await api('/api/cases',{method:'POST',body:JSON.stringify({request_id:requestID(),plan})});$('#case-dialog').close();await loadCases(c.id);toast('方案已保存')}catch(e){showErrors('#form-errors',e)}}
async function mutate(action,payload){const c=state.detail.case;try{const result=await api(`/api/cases/${c.id}/${action}`,{method:'POST',body:JSON.stringify({request_id:requestID(),revision:c.revision,...payload})});await loadCases(result.id);toast('操作已完成');return result}catch(e){if(e.data?.case){state.detail.case=e.data.case;await selectCase(c.id)}toast(e.message);throw e}}
function issueRow(values={}){const row=document.createElement('div');row.className='issue-row';row.innerHTML=`<label>问题代码<input data-key="code" value="${escapeHTML(values.code||'')}"></label><label>问题标题<input data-key="title" value="${escapeHTML(values.title||'')}"></label><label>关联字段<select data-key="field_path">${issueFields.map(x=>`<option value="${x}" ${values.field_path===x?'selected':''}>${planLabels[x]}</option>`).join('')}</select></label><label>修改建议<textarea data-key="suggestion">${escapeHTML(values.suggestion||'')}</textarea></label><button type="button" class="icon remove-row" aria-label="删除问题">×</button>`;row.querySelector('.remove-row').onclick=()=>row.remove();return row}
function openReviewDialog(){const c=state.detail.case,form=$('#review-form');form.reset();const done=new Set((c.review_seats||[]).filter(s=>s.completed).map(s=>s.discipline)),available=['arboriculture','construction'].find(x=>!done.has(x));if(available)form.elements.discipline.value=available;$('#issue-rows').innerHTML='';$('#issue-rows').append(issueRow({field_path:'protection_measures'}));$('#review-errors').textContent='';$('#review-dialog').showModal()}
async function submitReview(e){e.preventDefault();const f=e.currentTarget,d=new FormData(f),conclusion=d.get('conclusion'),issues=conclusion==='pass'?[]:[...$('#issue-rows').children].map(row=>Object.fromEntries([...row.querySelectorAll('[data-key]')].map(el=>[el.dataset.key,el.value])));try{await mutate('opinions',{discipline:d.get('discipline'),reviewer_name:d.get('reviewer_name'),conclusion,issues,basis:d.get('basis')});$('#review-dialog').close()}catch(e){showErrors('#review-errors',e)}}
function revisionPlanHTML(plan){return Object.entries(planLabels).map(([key,label])=>{const value=plan[key];if(key==='destination_ready')return `<label class="check"><input name="${key}" type="checkbox" ${value?'checked':''}>${label}</label>`;if(key==='health_grade')return `<label>${label}<select name="${key}">${['良好','一般','衰弱'].map(x=>`<option ${value===x?'selected':''}>${x}</option>`).join('')}</select></label>`;const numeric=['age_years','trunk_diameter_cm','root_ball_diameter_cm','transport_duration_hours'].includes(key),wide=['source_location','destination_location','migration_reason','protection_measures'].includes(key),textarea=['migration_reason','protection_measures'].includes(key);return `<label class="${wide?'wide':''}">${label}${textarea?`<textarea name="${key}" required>${escapeHTML(value)}</textarea>`:`<input name="${key}" ${numeric?'type="number"':''} required value="${escapeHTML(value)}">`}</label>`}).join('')}
function openRevisionDialog(){const c=state.detail.case,form=$('#revision-form');form.reset();form.elements.submitted_by.value='';$('#revision-plan').innerHTML=revisionPlanHTML(c.plan);$('#response-rows').innerHTML=(c.modification_items||[]).map(i=>`<article class="response-row data-row" data-code="${escapeHTML(i.issue_code)}"><h4>${escapeHTML(i.issue_code)} · ${escapeHTML(i.title)}</h4><p>${escapeHTML(planLabels[i.field_path]||i.field_path)} · ${escapeHTML(i.suggestion)}</p><label>响应<textarea data-key="response" required></textarea></label><label class="check"><input data-key="resolved" type="checkbox">已解决</label><label>无需字段变更说明<textarea data-key="no_change_reason"></textarea></label></article>`).join('');$('#attachment-rows').innerHTML='';$('#revision-errors').textContent='';form.oninput=renderRevisionPreview;renderRevisionPreview();$('#revision-dialog').showModal()}
function attachmentRow(){const row=document.createElement('div');row.className='attachment-row data-row';row.innerHTML='<label>名称<input data-key="name" required></label><label>类型<select data-key="content_type"><option value="application/pdf">PDF</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label><label>大小（bytes）<input data-key="size_bytes" type="number" min="1" max="52428800" required></label><label>SHA-256 摘要<input data-key="digest" required></label><button type="button" class="icon remove-row" aria-label="删除附件">×</button>';row.querySelector('.remove-row').onclick=()=>{row.remove();renderRevisionPreview()};return row}
function renderRevisionPreview(){const form=$('#revision-form'),before=state.detail.case.plan,after=planFromForm(form),changes=Object.keys(planLabels).filter(k=>String(before[k])!==String(after[k])),responses=[...$('#response-rows').children],covered=responses.filter(x=>x.querySelector('[data-key="response"]').value.trim()).length;$('#revision-preview').innerHTML=`<p>字段变化 ${changes.length} 项：${changes.map(x=>planLabels[x]).join('、')||'无'}</p><p>响应覆盖 ${covered} / ${responses.length}</p>`}
async function submitRevision(e){e.preventDefault();const form=e.currentTarget,plan=planFromForm(form),issue_responses=[...$('#response-rows').children].map(row=>({issue_code:row.dataset.code,response:row.querySelector('[data-key="response"]').value,resolved:row.querySelector('[data-key="resolved"]').checked,no_change_reason:row.querySelector('[data-key="no_change_reason"]').value})),attachment_metadata=[...$('#attachment-rows').children].map(row=>({name:row.querySelector('[data-key="name"]').value,content_type:row.querySelector('[data-key="content_type"]').value,size_bytes:Number(row.querySelector('[data-key="size_bytes"]').value),digest:row.querySelector('[data-key="digest"]').value}));try{await mutate('revisions',{plan,issue_responses,attachment_metadata,submitted_by:form.elements.submitted_by.value});$('#revision-dialog').close()}catch(e){showErrors('#revision-errors',e)}}
async function approve(){const approver=prompt('批准人');if(!approver)return;const note=prompt('批准意见','整改响应完整，技术规则复算无阻断项，同意批准归档。')||'';await mutate('approval',{approver_name:approver,decision_note:note}).catch(()=>{})}
function showErrors(selector,error){const fields=error.data?.error?.fields;$(selector).textContent=fields?Object.entries(fields).map(([k,v])=>`${planLabels[k]||k}：${v}`).join('；'):error.message}
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#new-case').onclick=()=>openCaseDialog();$$('.open-create').forEach(b=>b.onclick=()=>openCaseDialog());$$('.close-dialog').forEach(b=>b.onclick=()=>$('#case-dialog').close());$$('.close-review').forEach(b=>b.onclick=()=>$('#review-dialog').close());$$('.close-revision').forEach(b=>b.onclick=()=>$('#revision-dialog').close());$('#case-form').onsubmit=saveCase;$('#review-form').onsubmit=submitReview;$('#revision-form').onsubmit=submitRevision;$('#add-issue').onclick=()=>$('#issue-rows').append(issueRow());$('#add-attachment').onclick=()=>{$('#attachment-rows').append(attachmentRow());renderRevisionPreview()};$('#batch-select').onchange=e=>renderBatch(e.target.value);$('#audit-action').onchange=renderAudit;$('#audit-revision').oninput=renderAudit;$('#case-filters').onsubmit=e=>{e.preventDefault();state.list.page=1;loadCases().catch(x=>toast(x.message))};$('#clear-filters').onclick=()=>{$('#case-filters').reset();state.list.page=1;loadCases().catch(x=>toast(x.message))};$('#prev-page').onclick=()=>{state.list.page--;loadCases().catch(x=>toast(x.message))};$('#next-page').onclick=()=>{state.list.page++;loadCases().catch(x=>toast(x.message))};$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#panel-${b.dataset.tab}`).classList.add('active')});Promise.all([api('/api/rules').then(x=>state.rules=x.rules||[]),loadCases()]).catch(e=>toast(e.message));
